### ISSUE TITLE
Wrong order in method call

### ISSUE THREAD

**Issue by XavierMarchena** [cptanalatriste/aco-flowshop#1]
My friend found this project and wanted to use it for his college course, but he couldn't run it, so i look at it and noticed that the file AcoFlowShopWithIsula.java has a bug in line 47. This is the line that works:

double[][] problemRepresentation = getTaillardProblemFromFile(fileDataset, 5, 20);

**Comment by cptanalatriste** [comment]
Hi Xavier,

Thanks for using the Isula Framework. I just realized I didn't upload the last dataset I used for testing the algorithm. After you perform pull again, this data file should be available: https://github.com/cptanalatriste/aco-flowshop/blob/master/src/ta001.data

Using that datafile, no changes in the code are required.

**Comment by XavierMarchena** [comment]
Great! Everything is working fine
